In [1]:
print("abc")

abc

In [4]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 1.9 MB/s eta 0:00:05
   ------- -------------------------------- 1.8/9.7 MB 4.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 7.1 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 9.7 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 9.2 MB/s  0:00:01
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.3 MB 19.0 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 19.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 19.2 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 16.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 13.6 MB/s  0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.2

In [5]:
import pandas as pd

In [7]:
data=[1,2,3,4,5]
series=pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
#custom index
marks=pd.Series([90,70,90],index=['Maths','English','PT'])
marks

Maths      90
English    70
PT         90
dtype: int64

In [9]:
marks['Maths']

np.int64(90)

In [10]:
#creating series from dictionary
data_dict={'a':1,'b':2,'c':3}
series_dict=pd.Series(data_dict)
series_dict

a    1
b    2
c    3
dtype: int64

In [11]:
#creating scalar data
series=pd.Series(5,index=['Ram','Siya','Piruu'])
series

Ram      5
Siya     5
Piruu    5
dtype: int64

In [13]:
#accesing series data
marks=pd.Series([56,78,90],index=['Ram','Siya','Piruu'])
marks

Ram      56
Siya     78
Piruu    90
dtype: int64

In [ ]:
print(marks.iloc[0]) #position ko basis ma

56

In [15]:
# access by label
marks['Ram']

np.int64(56)

In [16]:
print(marks['Ram'])

56

In [17]:
#series real example
stock_prices=pd.Series([123,456,345,123,345],index=['Sunday','Monday','Tuesday','Wednesday','Thursday'])

In [18]:
print(stock_prices['Tuesday'])

345

In [19]:
print(stock_prices.mean())

278.4

In [20]:
print(stock_prices.max())

456

In [21]:
print(stock_prices.min())

123

In [22]:
print(stock_prices[stock_prices>150])

Monday      456
Tuesday     345
Thursday    345
dtype: int64

In [23]:
print(stock_prices>150)

Sunday       False
Monday        True
Tuesday       True
Wednesday    False
Thursday      True
dtype: bool

In [24]:
#DataFrame with two-dimensional data with row and columns.
data={
    'Name':['Anita','Siya','Rekha'],
    'Age':[23,45,78],
    'City':['New York','KTM','MnR']
}

In [25]:
df=pd.DataFrame(data)
df

    Name  Age      City
0  Anita   23  New York
1   Siya   45       KTM
2  Rekha   78       MnR

In [ ]:
df.head(1) #first one

    Name  Age      City
0  Anita   23  New York

In [ ]:
df.tail(1) # last one

    Name  Age City
2  Rekha   78  MnR

In [ ]:
df.shape # count grxa row ra columns lai

(3, 3)

In [29]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [30]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [31]:
df.describe

<bound method NDFrame.describe of     Name  Age      City
0  Anita   23  New York
1   Siya   45       KTM
2  Rekha   78       MnR>

In [32]:
df.describe()

             Age
count   3.000000
mean   48.666667
std    27.682726
min    23.000000
25%    34.000000
50%    45.000000
75%    61.500000
max    78.000000

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [34]:
df['Name']

0    Anita
1     Siya
2    Rekha
Name: Name, dtype: str

In [35]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [37]:
df[['Name','Age']]

    Name  Age
0  Anita   23
1   Siya   45
2  Rekha   78

In [38]:
# access by position rowwise
df.iloc[0]

Name       Anita
Age           23
City    New York
Name: 0, dtype: object

In [39]:
# filtering dataframe
filtered_df=df[df['Age'] > 28]
filtered_df

    Name  Age City
1   Siya   45  KTM
2  Rekha   78  MnR

In [ ]:
#multiple conditions
# And Conditions
filtered_df=df[(df['Age'] > 26) & (df['City'] == 'KTM')]
filtered_df

   Name  Age City
1  Siya   45  KTM

In [42]:
# OR Conditions
filtered_df=df[(df['Age'] > 26) | (df['City'] == 'KTM')]
filtered_df

    Name  Age City
1   Siya   45  KTM
2  Rekha   78  MnR

In [43]:
#CRUD 
#Adding a new column
df['Salary']=[50000,30000,67000]
df

    Name  Age      City  Salary
0  Anita   23  New York   50000
1   Siya   45       KTM   30000
2  Rekha   78       MnR   67000

In [44]:
#updating existing column
df['Salary']=df['Salary']+5000
df

    Name  Age      City  Salary
0  Anita   23  New York   55000
1   Siya   45       KTM   35000
2  Rekha   78       MnR   72000

In [45]:
#updating existing column with conditions
df.loc[df['Age'] > 30, 'Salary']=df['Salary']+100
df

    Name  Age      City  Salary
0  Anita   23  New York   55000
1   Siya   45       KTM   35100
2  Rekha   78       MnR   72100

In [46]:
#deleting  a column
df.drop('Salary', axis=1, inplace=True)
df

    Name  Age      City
0  Anita   23  New York
1   Siya   45       KTM
2  Rekha   78       MnR

In [48]:
#deleting  a row
df.drop(0, axis=0, inplace=True)
df

    Name  Age City
1   Siya   45  KTM
2  Rekha   78  MnR

In [ ]:
#Read a CSV file
df=pd.read_csv('sample_Pandas.csv')

In [52]:
print(df)

    first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr
1    Josephine    Darakjy          Chanay, Jeffrey A Esq
2          Art     Venere            Chemel, James L Cpa
3        Lenna   Paprocki         Feltz Printing Service
4      Donette     Foller            Printing Dimensions
..         ...        ...                            ...
495    Brittni  Gillaspie                    Inner Label
496    Raylene      Kampa                     Hermar Inc
497        Flo   Bookamer   Simonton Howe & Schneider Pc
498       Jani      Biddy  Warehouse Office & Paper Prod
499   Chauncey     Motley     Affiliated With Travelodge

                  address        city      county state    zip        phone1  \
0      6649 N Blue Gum St         NaN     Orleans    LA  70116  504-621-8927
1     4 B Blue Ridge Blvd    Brighton  Livingston    MI  48116  810-292-9388
2    8 W Cerritos Ave #54  Bridgeport  Gloucester    NJ   8014  856-636-8749
3             639 Main St   Anchorage   Anchorage    AK  99501  907-385-4412
4            34 Center St    Hamilton      Butler    OH  45011  513-570-1893
..                    ...         ...         ...   ...    ...           ...
495            67 Rv Cent       Boise         Ada    ID  83709  208-709-1235
496        2 Sw Nyberg Rd     Elkhart     Elkhart    IN  46514  574-499-1454
497       89992 E 15th St    Alliance   Box Butte    NE  69301  308-726-2182
498      61556 W 20th Ave     Seattle        King    WA  98104  206-711-6498
499        63 E Aurora Dr     Orlando      Orange    FL  32804  407-413-4842

           phone2                          email  \
0    504-845-1427                jbutt@gmail.com
1    810-374-9840  josephine_darakjy@darakjy.org
2    856-264-4130                 art@venere.org
3    907-921-2010          lpaprocki@hotmail.com
4    513-549-4561         donette.foller@cox.net
..            ...                            ...
495  208-206-9848       bgillaspie@gillaspie.com
496  574-330-1884               rkampa@kampa.org
497  308-250-6987           flo.bookamer@cox.net
498  206-395-6284               jbiddy@yahoo.com
499  407-557-8857        chauncey_motley@aol.com

                                         web
0               http://www.bentonjohnbjr.com
1           http://www.chanayjeffreyaesq.com
2             http://www.chemeljameslcpa.com
3        http://www.feltzprintingservice.com
4          http://www.printingdimensions.com
..                                       ...
495                http://www.innerlabel.com
496                 http://www.hermarinc.com
497   http://www.simontonhoweschneiderpc.com
498  http://www.warehouseofficepaperprod.com
499  http://www.affiliatedwithtravelodge.com

[500 rows x 12 columns]

In [53]:
df.head()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [54]:
df.tail()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [55]:
df.isnull()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False

In [56]:
df.shape

(500, 12)